openapi: 3.0.0
info:
  description: API to predict the sale for third month using ML Model
  version: "1.0.0"
  title: Sales Forecast
servers:
  - url: https://ml-deployment-swagger.herokuapp.com/api/v1/sales_forecast
    description: Main (production) server
  - url: http://0.0.0.0:5000/api/v1/sales_forecast
    description: Internal staging server for testing

# Paths supported by the server application
paths:
  /sale:
    get:
      operationId: predict_sale.predictSaleFunc
      tags:
        - sale
      summary: Returns the predicted sale's price
      description: Returns the predicted sale's price of third month based on sale in first, second month and rate of interest.
      parameters:
        - name: rate
          in: query
          description: rate of interest
          schema:
            type: number
          example:
            4
          style: form
          explode: true
          required: True
        - name: sale1
          in: query
          description: sale in first month
          schema:
            type: number
          example:
            234.44
          style: form
          explode: true
          required: True
        - name: sale2
          in: query
          description: sale in second month
          schema:
            type: number
          example:
            254.84
          style: form
          explode: true
          required: True
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  sale3:
                    type: number
                example:
                  "sale3": 738.49